version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/auth-service-777-task-definition:latest"
        LoadBalancerInfo:
          ContainerName: "auth-service-777"
          ContainerPort: "2000"
        PlatformVersion: "LATEST"